server:
  port: 8080
spring:
  profiles:
    active: dev
  banner:
    location: ["classpath:banner.txt", "file:./banner.txt"]
  freemarker:
    suffix: .ftl
    cache: false
    settings:
      template_exception_handler: rethrow
      number_format: 0.##
    template-loader-path: ["classpath:/templates/", "file:./templates/"]
  messages:
    basename: i18n/message
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
  #default disable flyway
  flyway:
    enabled: false

#  resources:
#    static-locations: ["classpath:static/", "file:./static/"]

# 配置mapper.xml位置，这个位置可以在pom.xml里配置
mybatis-plus:
  mapper-locations: classpath:/*Mapper.xml
  global-config:
    banner: false
    db-config:
      logic-delete-field: isDeleted # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值
      logic-not-delete-value: 0 # 逻辑未删除值