site:
  datasource_driver: com.mysql.cj.jdbc.Driver
  datasource_url: jdbc:mysql://localhost:3306/ifc_bbs?useSSL=false&characterEncoding=utf8&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
  datasource_username: root
  datasource_password: Admin123
web:
  wallet:
    ifc:
      #regtest net node ip
      regtestHost: 192.168.2.7

# 想看mybatis执行的sql的时候，去掉下面这段的注释
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
spring:
  flyway:
    enabled: true